<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLpgx3as\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLpgx3as/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLpgx3as.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLpgx3as\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLpgx3as\appDevDebugProjectContainer([
    'container.build_hash' => 'Lpgx3as',
    'container.build_id' => '3d878a04',
    'container.build_time' => 1661935403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLpgx3as');
